# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mateusz/clion-2017.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/mateusz/clion-2017.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mateusz/Dokumenty/SO2_proj/Projekt_SO/program

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mateusz/Dokumenty/SO2_proj/Projekt_SO/program/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mateusz/clion-2017.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mateusz/clion-2017.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusz/Dokumenty/SO2_proj/Projekt_SO/program/cmake-build-debug/CMakeFiles /home/mateusz/Dokumenty/SO2_proj/Projekt_SO/program/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateusz/Dokumenty/SO2_proj/Projekt_SO/program/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program
.PHONY : program

# fast build rule for target.
program/fast:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/build
.PHONY : program/fast

Farmer.o: Farmer.cpp.o

.PHONY : Farmer.o

# target to build an object file
Farmer.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Farmer.cpp.o
.PHONY : Farmer.cpp.o

Farmer.i: Farmer.cpp.i

.PHONY : Farmer.i

# target to preprocess a source file
Farmer.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Farmer.cpp.i
.PHONY : Farmer.cpp.i

Farmer.s: Farmer.cpp.s

.PHONY : Farmer.s

# target to generate assembly for a file
Farmer.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Farmer.cpp.s
.PHONY : Farmer.cpp.s

Field.o: Field.cpp.o

.PHONY : Field.o

# target to build an object file
Field.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Field.cpp.o
.PHONY : Field.cpp.o

Field.i: Field.cpp.i

.PHONY : Field.i

# target to preprocess a source file
Field.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Field.cpp.i
.PHONY : Field.cpp.i

Field.s: Field.cpp.s

.PHONY : Field.s

# target to generate assembly for a file
Field.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Field.cpp.s
.PHONY : Field.cpp.s

Road.o: Road.cpp.o

.PHONY : Road.o

# target to build an object file
Road.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Road.cpp.o
.PHONY : Road.cpp.o

Road.i: Road.cpp.i

.PHONY : Road.i

# target to preprocess a source file
Road.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Road.cpp.i
.PHONY : Road.cpp.i

Road.s: Road.cpp.s

.PHONY : Road.s

# target to generate assembly for a file
Road.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Road.cpp.s
.PHONY : Road.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... program"
	@echo "... Farmer.o"
	@echo "... Farmer.i"
	@echo "... Farmer.s"
	@echo "... Field.o"
	@echo "... Field.i"
	@echo "... Field.s"
	@echo "... Road.o"
	@echo "... Road.i"
	@echo "... Road.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

